---

- name: delete /home/ubuntu/code if exists
  file:
    path: /home/ubuntu/code
    state: absent

- name: git clone project files
  git:
    repo: https://github.com/infinite1/ccc-ass2.git
    dest: /home/ubuntu/code
    
# proxy settings for docker
- name: mkdir /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  become: yes

- name: touch /etc/systemd/system/docker.service.d/http-proxy.conf file
  file:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: touch
  become: yes

- name: Add proxy in /etc/systemd/system/docker.service.d/http-proxy.conf
  become: yes
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    block: |
      [Service]
      Environment="HTTP_PROXY=http://proxy.example.com:80/" "HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/" "HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/" "http_proxy=http://wwwproxy.unimelb.edu.au:8000/" "https_proxy=http://wwwproxy.unimelb.edu.au:8000/" "no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au"

- name: mkdir /home/ubuntu/.docker
  file:
    path: /home/ubuntu/.docker
    state: directory
  become: yes

- name: touch /home/ubuntu/.docker/config.json
  file:
    path: /home/ubuntu/.docker/config.json
    state: touch
  become: yes

- name: Add proxy in /home/ubuntu/.docker/config.json
  become: yes
  lineinfile:
    path: /home/ubuntu/.docker/config.json
    line: '{"proxies":{"default":{"httpProxy":"http://wwwproxy.unimelb.edu.au:8000","httpsProxy":"http://wwwproxy.unimelb.edu.au:8000","noProxy":"localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbounre.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"}}}'
    create: yes

- name: Flush changes
  shell: systemctl daemon-reload
  become: yes

- name: Restart Docker
  shell: systemctl restart docker 
  become: yes

- name: add host to known hosts
  become: yes
  lineinfile:
    path: /home/ubuntu/code/demo_website/demo_website/settings.py
    regexp: '^ALLOWED_HOSTS'
    line: ALLOWED_HOSTS = ["{{ ansible_default_ipv4.address }}"]

- debug:
    msg: "IP address is {{ ansible_default_ipv4.address }}"

- name: run web server
  become: yes
  docker_compose:
        project_src: /home/ubuntu/code/demo_website
        build: yes

  