- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true
  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: all
  gather_facts: true
  roles:
    - role: set-environment
    - role: deploy-webserver