---
- name: delete /home/ubuntu/code if exists
  file:
    path: /home/ubuntu/code
    state: absent

- name: git clone project files
  environment:
    http_proxy: http://wwwproxy.unimelb.edu.au:8000/
    HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/ 
    HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/ 
    https_proxy: http://wwwproxy.unimelb.edu.au:8000/ 
    ftp_proxy: http://wwwproxy.unimelb.edu.au:8000
    no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au
  git:
    repo: https://github.com/infinite1/ccc-ass2.git
    version: babala
    dest: /home/ubuntu/code

- name: set proxy
  become: yes
  shell: |
    sudo echo 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"
    https_proxy="http://wwwproxy.unimelb.edu.au:8000"
    ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"' >> /etc/environment