# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: instance-01-vol
    vol_size: 10
  - vol_name: instance-02-vol
    vol_size: 10
  - vol_name: instance-03-vol
    vol_size: 10
  - vol_name: instance-04-vol
    vol_size: 10


# Security group
security_groups:
  - name: ssh
    description: "SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-01
    volumes: ['instance-01-vol']
  - name: instance-02
    volumes: ['instance-02-vol']
  - name: instance-03
    volumes: ['instance-03-vol']
  - name: instance-04
    volumes: ['instance-04-vol']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: xinyu-key
instance_flavor: uom.mse.1c4g