# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: test-babala-vol
    vol_size: 10


# Security group
security_groups:
  - name: ssh
    description: "SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: babala
    volumes: ['test-babala-vol']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: key-test
instance_flavor: uom.mse.2c9g