---
# image is from https://github.com/dockersamples/docker-swarm-visualizer
- name: Set docker swarm visualizer
  become: yes
  docker_swarm_service:
    name: viz
    image: dockersamples/visualizer
    publish: 
      - published_port: 70
        target_port: 8080
    constraints: node.role==manager
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock

